apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: telemetry-log-agent
  name: telemetry-log-agent
  namespace: kyma-system
data:
  relay: |
    exporters:
      otlp:
        endpoint: log-receiver.log-load-test:4317 # export directly to backend
        tls:
          insecure: true
        retry_on_failure:
            enabled: false
        sending_queue:
          enabled: false

    extensions:
      file_storage:
        directory: /var/lib/otelcol
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
      pprof:
        endpoint: 127.0.0.1:1777

    processors:
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      transform/set-instrumentation-scope-runtime:
        error_mode: ignore
        metric_statements:
            - context: scope
              statements:
                - set(version, "main")
                - set(name, "io.kyma-project.telemetry/runtime")
      k8sattributes:                                                                                                                                                                                                                                  
        auth_type: serviceAccount                                                                                                                                                                                                                   
        passthrough: false                                                                                                                                                                                                                          
        extract:                                                                                                                                                                                                                                    
            metadata:                                                                                                                                                                                                                               
                - k8s.pod.name                                                                                                                                                                                                                      
                - k8s.node.name                                                                                                                                                                                                                     
                - k8s.namespace.name                                                                                                                                                                                                                
                - k8s.deployment.name                                                                                                                                                                                                               
                - k8s.statefulset.name                                                                                                                                                                                                              
                - k8s.daemonset.name                                                                                                                                                                                                                
                - k8s.cronjob.name                                                                                                                                                                                                                  
                - k8s.job.name                                                                                                                                                                                                                      
            labels:                                                                                                                                                                                                                                 
                - from: pod                                                                                                                                                                                                                         
                  key: app.kubernetes.io/name                                                                                                                                                                                                       
                  tag_name: kyma.kubernetes_io_app_name                                                                                                                                                                                             
                - from: pod                                                                                                                                                                                                                         
                  key: app                                                                                                                                                                                                                          
                  tag_name: kyma.app_name                                                                                                                                                                                                           
        pod_association:                                                                                                                                                                                                                            
            - sources:                                                                                                                                                                                                                              
                - from: resource_attribute                                                                                                                                                                                                          
                  name: k8s.pod.ip                                                                                                                                                                                                                  
            - sources:                                                                                                                                                                                                                              
                - from: resource_attribute                                                                                                                                                                                                          
                  name: k8s.pod.uid                                                                                                                                                                                                                 
            - sources:                                                                                                                                                                                                                              
                - from: connection
      resource/insert-cluster-name:                                                                                                                                                                                                                   
          attributes:                                                                                                                                                                                                                                 
              - action: insert                                                                                                                                                                                                                        
                key: k8s.cluster.name                                                                                                                                                                                                                 
                value: blabala 

    receivers:
      filelog:
        exclude:
        - /var/log/pods/kyma-system_telemetry-log-agent*/*/*.log # exclude self
        - /var/log/pods/kyma-system_telemetry-fluent-bit*/*/*.log # exclude FluentBit
        include:
        - /var/log/pods/*/*/*.log
        include_file_name: false
        include_file_path: true
        operators:
        - type: container
          id: container-parser
          add_metadata_from_filepath: true
          format: containerd
        - from: attributes.stream
          if: attributes.stream != nil
          to: attributes["log.iostream"]
          type: move
        - if: body matches "^{.*}$"
          parse_from: body
          parse_to: attributes
          type: json_parser
        - from: body
          to: attributes.original
          type: copy
        - from: attributes.message
          if: attributes.message != nil
          to: body
          type: move
        - from: attributes.msg
          if: attributes.msg != nil
          to: body
          type: move
        - if: attributes.level != nil
          parse_from: attributes.level
          type: severity_parser
        retry_on_failure:
          enabled: true
        start_at: beginning
        storage: file_storage

    service:
      extensions:
      - health_check
      - pprof
      - file_storage
      pipelines:
        logs:
          exporters:
          - otlp
          processors:
          - memory_limiter
          - transform/set-instrumentation-scope-runtime
          - k8sattributes
          - resource/insert-cluster-name
          receivers:
          - filelog
      telemetry:
        metrics:
          readers:
          - pull:
              exporter:
                prometheus:
                  host: ${MY_POD_IP}
                  port: 8888