---
apiVersion: v1
kind: Namespace
metadata:
  name: log-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-tls
  namespace: log-tls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-tls
  template:
    metadata:
      labels:
        app: log-tls
      name: log-tls
    spec:
      containers:
        - args:
            - -i http
            - -o stdout
            - -q
          image: fluent/fluent-bit:latest
          livenessProbe:
            tcpSocket:
              port: http-ingest
          name: log-tls
          ports:
            - containerPort: 9880
              name: http-ingest
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: http-ingest
---
apiVersion: v1
kind: Service
metadata:
  name: log-tls
  namespace: log-tls
spec:
  ports:
    - name: http-ingest
      port: 9880
      protocol: TCP
      targetPort: http-ingest
  selector:
    app: log-tls
---
apiVersion: v1
kind: Namespace
metadata:
  name: log-gen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-gen
  namespace: log-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-gen
  template:
    metadata:
      labels:
        app: log-gen
    spec:
      containers:
        - image: mingrammer/flog:latest
          name: flog
          args:
            - -b=64
            - -f=json
            - -l
---
apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: tls-ca-missing
spec:
  input:
    application:
      namespaces:
        include:
          - log-gen
  output:
    http:
      dedot: true
      host:
        value: log-tls.log-tls.svc.cluster.local
      port: "9880"
      uri: /
      format: json
      tls:
        disabled: true
        skipCertificateValidation: true
