---
apiVersion: v1
kind: Namespace
metadata:
  name: metric-tls
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metric-tls-config
  namespace: metric-tls
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    exporters:
      debug:
        verbosity: detailed
    service:
      pipelines:
        metrics:
          receivers:
            - otlp
          exporters:
            - debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-tls
  namespace: metric-tls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-tls
  strategy: {}
  template:
    metadata:
      labels:
        app: metric-tls
    spec:
      volumes:
        - name: config
          configMap:
            name: metric-tls-config
      securityContext:
        fsGroup: 101
      containers:
        - image: otel/opentelemetry-collector-contrib:latest
          name: collector
          volumeMounts:
            - name: config
              mountPath: /etc/collector
          args:
            - --config=/etc/collector/config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: metric-tls
  namespace: metric-tls
spec:
  ports:
    - name: grpc-otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: http-otlp
      port: 4318
      protocol: TCP
      targetPort: 4318
  selector:
    app: metric-tls
---
apiVersion: v1
kind: Namespace
metadata:
  name: metric-gen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-gen
  namespace: metric-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-gen
  template:
    metadata:
      labels:
        app: metric-gen
    spec:
      containers:
        - image: ghcr.io/skhalash/examples/monitoring-custom-metrics:3d41736
          imagePullPolicy: IfNotPresent
          name: metric-gen
          ports:
            - containerPort: 8080
              name: http-metrics
              protocol: TCP
          resources:
            limits:
              memory: 100Mi
            requests:
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  name: metric-gen-metrics
  namespace: metric-gen
spec:
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: metric-gen
  type: ClusterIP
---
apiVersion: telemetry.kyma-project.io/v1alpha1
kind: MetricPipeline
metadata:
  name: tls-ca-missing-secret
spec:
  input:
    runtime:
      enabled: true
      namespaces:
        include: 
          - foo
        exclude:
          - bar
    prometheus:
      enabled: true
    istio:
      enabled: true
  output:
    otlp:
      endpoint:
        value: http://metric-tls.metric-tls:4317
      tls:
        cert:
          value: |
            -----BEGIN CERTIFICATE-----
            MIICgzCCAeygAwIBAgIUB7yRTrBuy/xL2GR3acRZvxKaEHMwDQYJKoZIhvcNAQEL
            BQAwYDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk5ZMREwDwYDVQQHDAhOZXcgWW9y
            azEaMBgGA1UECgwRTW9jayBPcmdhbml6YXRpb24xFTATBgNVBAMMDHd3dy5tb2Nr
            LmNvbTAgFw0yNDA2MjQwOTI5MzZaGA81MDI0MDMxOTE0MjQxNFowYDELMAkGA1UE
            BhMCVVMxCzAJBgNVBAgMAk5ZMREwDwYDVQQHDAhOZXcgWW9yazEaMBgGA1UECgwR
            TW9jayBPcmdhbml6YXRpb24xFTATBgNVBAMMDHd3dy5tb2NrLmNvbTCBnzANBgkq
            hkiG9w0BAQEFAAOBjQAwgYkCgYEA2y8lHVSE9b2EmERGa1Y+hMNAhKb1v3891466
            0E38X0IbLESKfsLNG+9mzz+xqSsjX3fLxsr3wCbbmV5jZb4Rs0C2FLMFZiRQzr+A
            t+bvN0SNB7GsjFNMYzTmtuUDlOS7w3Ps9mFDdh3KusgIj5+qJ06EA/UnFONrRGFK
            BMvgHDsCAwEAAaM4MDYwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCBaAwFgYD
            VR0lAQH/BAwwCgYIKwYBBQUHAwEwDQYJKoZIhvcNAQELBQADgYEAMV1fb/4YhEBa
            Uh0DODdZSpXPETGmIV+o9/gVgnVO/Ds+xqIKAFX7/8vbaooxzxlEwkYKFmIrO336
            IQIphTZefXB8wcN0lbhRN1UI2IHTzvQBPjvvlTtv8xbnjrsoaj/RjdroFRZFaTYx
            fQyIWzaKL3E301Thr6ufUzcjezXugDs=
            -----END CERTIFICATE-----
        key:
          value: |
            -----BEGIN RSA PRIVATE KEY-----
            MIICXgIBAAKBgQDbLyUdVIT1vYSYREZrVj6Ew0CEpvW/fz3XjrrQTfxfQhssRIp+
            ws0b72bPP7GpKyNfd8vGyvfAJtuZXmNlvhGzQLYUswVmJFDOv4C35u83RI0HsayM
            U0xjNOa25QOU5LvDc+z2YUN2Hcq6yAiPn6onToQD9ScU42tEYUoEy+AcOwIDAQAB
            AoGAbFpcEKnNqOXtfJCT91AFTAByDqGy7t3qJnuqontK/ZRidnnTtWJ7nwm0W1Pz
            cdufevxvwnBoFZegC6t7m7pgaMCqLUNy9blVc7MIQC97RxchdTckjIRL7jSkG2hL
            /yHIyubMfhdzsx/0YxvUnAxa+9jnWvmDo+Yp6e/3/3XmOJECQQDt6BX+CPK1e+Wa
            vvGWOy0erJeKQn2IHSubMEBDr53qNKhDu9chFD/z1tAkp0w7m4ACYBPkOvcqGonB
            GH4ngPZFAkEA69qLH6BCmRSvbPKM3zD+MoPf5TcsYwlE5wVOcFeOgPffyUzpzcz9
            FaYz3qEYJR6pKcIlogZSprNLVr1T5eUwfwJBAJ3P0y7VHrLWQeNZgAXosTBkyo0z
            N/QfbXqfEjIT/4uJbIipxLWzqgyE1UNLGp17s/lfZDKEDsqGGhTVu3FW8YUCQQCX
            DFvVYVnFmE3RRHWb61ChIXwe3Hr84k7Sdb+Ki0ikqBsWXL/QIdxkJRFLH3jLLRvB
            tqlLXylHwcQaRR6aOXIZAkEAwKHc5Ueb86nD/s/5AjukBhEW86G56sxbbOMt1lNA
            cSKwQXGt4Yz7dQRtOHNoZtIibvAJYtmJIxpAuKLNpFPq2A==
            -----END RSA PRIVATE KEY-----
        ca:
          valueFrom:
            secretKeyRef:
              name: thisShouldNotExistName
              namespace: thisShouldNotExistNS
              key: thisShouldNotExistKey
