apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "22"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"log-load-generator","namespace":"log-load-test"},"spec":{"replicas":30,"selector":{"matchLabels":{"app.kubernetes.io/name":"logs-load-generator"}},"template":{"metadata":{"labels":{"app.kubernetes.io/name":"logs-load-generator"}},"spec":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app.kubernetes.io/name","operator":"In","values":["logs-load-generator"]}]},"topologyKey":"kubernetes.io/hostname"},"weight":100}]}},"containers":[{"args":["-n=10","-f=json","-l"],"image":"mingrammer/flog","imagePullPolicy":"Always","name":"flog","resources":{"limits":{"cpu":"10m","memory":"200Mi"},"requests":{"cpu":"10m","memory":"50Mi"}}}]}}}}
  creationTimestamp: "2025-01-15T12:43:21Z"
  generation: 50
  name: log-load-generator
  namespace: log-load-test
  resourceVersion: "16358260"
  uid: fc5d9e1f-aa8f-479d-9d59-836d2e48cb97
spec:
  progressDeadlineSeconds: 600
  replicas: 60
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: logs-load-generator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-01-21T09:25:39+01:00"
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: logs-load-generator
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - logs-load-generator
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - -f=json
        - -l
        image: mingrammer/flog
        imagePullPolicy: Always
        name: flog
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 60
  conditions:
  - lastTransitionTime: "2025-01-21T08:22:45Z"
    lastUpdateTime: "2025-01-21T08:22:45Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-01-15T12:43:21Z"
    lastUpdateTime: "2025-01-21T08:26:19Z"
    message: ReplicaSet "log-load-generator-645f5794c5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 50
  readyReplicas: 60
  replicas: 60
  updatedReplicas: 60
