apiVersion: v1
kind: ConfigMap
metadata:
  labels:
      app.kubernetes.io/name: telemetry-log-gateway
  name: telemetry-log-gateway
  namespace: kyma-system
data:
  relay.conf: |
      extensions:
          health_check:
              endpoint: ${MY_POD_IP}:13133
          pprof:
              endpoint: 127.0.0.1:1777
      service:
          pipelines:
              logs/load-test-1:
                  receivers:
                      - otlp
                  processors:
                      - memory_limiter
                      - k8sattributes
                      - resource/insert-cluster-name
                      - batch
                  exporters:
                      - otlp/load-test-1
          telemetry:
              metrics:
                  readers:
                      - pull:
                          exporter:
                              prometheus:
                                  host: ${MY_POD_IP}
                                  port: 8888
              logs:
                  level: info
                  encoding: json
          extensions:
              - health_check
              - pprof
      receivers:
          otlp:
              protocols:
                  http:
                      endpoint: ${MY_POD_IP}:4318
                  grpc:
                      endpoint: ${MY_POD_IP}:4317
      processors:
          batch:
              send_batch_size: 2000
              timeout: 10s
              send_batch_max_size: 2000
          memory_limiter:
              check_interval: 1s
              limit_percentage: 75
              spike_limit_percentage: 15
          k8sattributes:
              auth_type: serviceAccount
              passthrough: false
              extract:
                  metadata:
                      - k8s.pod.name
                      - k8s.node.name
                      - k8s.namespace.name
                      - k8s.deployment.name
                      - k8s.statefulset.name
                      - k8s.daemonset.name
                      - k8s.cronjob.name
                      - k8s.job.name
                  labels:
                      - from: pod
                      key: app.kubernetes.io/name
                      tag_name: kyma.kubernetes_io_app_name
                      - from: pod
                      key: app
                      tag_name: kyma.app_name
              pod_association:
                  - sources:
                      - from: resource_attribute
                      name: k8s.pod.ip
                  - sources:
                      - from: resource_attribute
                      name: k8s.pod.uid
                  - sources:
                      - from: connection
          resource/insert-cluster-name:
              attributes:
                  - action: insert
                  key: k8s.cluster.name
                  value: ${KUBERNETES_SERVICE_HOST}
      exporters:
          otlp/load-test-1:
              compression:
              none
              endpoint: ${OTLP_ENDPOINT_LOAD_TEST_1}
              tls:
                  insecure: true
                  insecure_skip_verify: true
              sending_queue:
                  enabled: true
                  queue_size: 256
              retry_on_failure:
                  enabled: true
                  initial_interval: 5s
                  max_interval: 30s
                  max_elapsed_time: 300s