{
 "title": "KCP / Consumption Reporter (Runtime)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "shoot_name",
    "query": {
     "query": "label_values(infrastructure_manager_im_runtime_state, shootName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "kcr_metering_runtime_state{shoot_name=\"$shoot_name\", state=\"billable\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Node Meter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Cost",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kcr_metering_node_cost{shoot_name=\"$shoot_name\"}) by (type)",
     "legendFormat": "{{type}}"
    },
    { "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "VM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kcr_metering_node_vm{shoot_name=\"$shoot_name\"}) by (type)",
     "legendFormat": "{{type}}"
    },
    { "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kcr_calculation_node_usage_per_meter_total{shoot_name=\"$shoot_name\", meter_id=\"node\"}[5m]))",
     "legendFormat": "node block hours"
    }
   ]
  },
  { "title": "PVC Meter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Size (Exact)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(kcr_metering_pvc_size_exact{shoot_name=\"$shoot_name\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Size (Rounded)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(kcr_metering_pvc_size_exact{shoot_name=\"$shoot_name\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(kcr_metering_pvc_count{shoot_name=\"$shoot_name\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(kcr_calculation_storage_usage_per_meter_total{shoot_name=\"$shoot_name\", meter_id=\"pvc\"}[5m]))",
     "legendFormat": "storage block hours"
    }
   ]
  },
  { "title": "Redis Meter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Size (Exact)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(kcr_metering_redis_size_exact{shoot_name=\"$shoot_name\"}) by (tier)",
     "legendFormat": "{{tier}}"
    }
   ]
  },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "sum(kcr_metering_redis_count{shoot_name=\"$shoot_name\"}) by (tier)",
     "legendFormat": "{{tier}}"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(kcr_calculation_storage_usage_per_meter_total{shoot_name=\"$shoot_name\", meter_id=\"redis\"}[5m]))",
     "legendFormat": "storage block hours"
    }
   ]
  },
  { "title": "VSC Meter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Size (Exact)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(kcr_metering_vsc_size_exact{shoot_name=\"$shoot_name\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Size (Rounded)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "sum(kcr_metering_vsc_size_rounded{shoot_name=\"$shoot_name\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "sum(kcr_metering_vsc_count{shoot_name=\"$shoot_name\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(kcr_calculation_storage_usage_per_meter_total{shoot_name=\"$shoot_name\", meter_id=\"vsc\"}[5m]))",
     "legendFormat": "storage block hours"
    }
   ]
  },
  { "title": "Fallback Meter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Fallback Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kcr_metering_fallback_errors_total{shoot_name=\"$shoot_name\"}[5m])) by (submeter_id)",
     "legendFormat": "{{submeter_id}}"
    }
   ]
  },
  {
   "title": "Submeter Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kcr_metering_fallback_submeter_errors_total{shoot_name=\"$shoot_name\"}[5m])) by (submeter_id)",
     "legendFormat": "{{submeter_id}}"
    }
   ]
  },
  {
   "title": "Cache Reads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kcr_metering_fallback_cache_reads_total{shoot_name=\"$shoot_name\"}[5m])) by (submeter_id)",
     "legendFormat": "{{submeter_id}}"
    }
   ]
  }
 ]
}