{
 "title": "KCP / Consumption Reporter (Runtime)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "shoot_name",
    "query": {
     "query": "label_values(infrastructure_manager_im_runtime_state, shootName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kcr_metering_runtime_state{shoot_name=\"$shoot_name\", state=\"billable\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Node Hours /1h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "nh/h" } },
   "targets": [
    {
     "expr": "sum(increase(kcr_calculation_node_usage_total{shoot_name=\"$shoot_name\"}[1h]))",
     "legendFormat": "node hours"
    }
   ]
  },
  {
   "title": "Storage Block Hours / 1h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sbh/h" } },
   "targets": [
    {
     "expr": "sum(increase(kcr_calculation_storage_usage_total{shoot_name=\"$shoot_name\"}[1h]))",
     "legendFormat": "storage block hours"
    }
   ]
  },
  {
   "title": "Capacity Units / 1h",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cu/h" } },
   "yaxes": [
    { "format": "cu/h" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kcr_calculation_price_per_meter_total{shoot_name=\"$shoot_name\"}[1h]))",
     "legendFormat": "capacity units (sum)"
    },
    {
     "expr": "sum(increase(kcr_calculation_price_total{shoot_name=\"$shoot_name\"}[1h]))",
     "legendFormat": "reported capacity units (total - free resources)"
    }
   ]
  },
  { "title": "Fallback Meter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Fallback Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kcr_metering_fallback_errors_total{shoot_name=\"$shoot_name\"}[5m])) by (submeter_id)",
     "legendFormat": "{{submeter_id}}"
    }
   ]
  },
  {
   "title": "Submeter Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kcr_metering_fallback_submeter_errors_total{shoot_name=\"$shoot_name\"}[5m])) by (submeter_id)",
     "legendFormat": "{{submeter_id}}"
    }
   ]
  },
  {
   "title": "Cache Reads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kcr_metering_fallback_cache_reads_total{shoot_name=\"$shoot_name\"}[5m])) by (submeter_id)",
     "legendFormat": "{{submeter_id}}"
    }
   ]
  },
  { "title": "Node Meter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Cost (Node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "n" } },
   "targets": [
    {
     "expr": "sum(kcr_metering_node_cost{shoot_name=\"$shoot_name\"}) by (type) or 0",
     "legendFormat": "{{type}}"
    },
    { "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "VM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kcr_metering_node_vm{shoot_name=\"$shoot_name\"}) by (type)",
     "legendFormat": "{{type}}"
    },
    { "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Usage /1h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "nh/h" } },
   "targets": [
    {
     "expr": "sum(increase(kcr_calculation_node_usage_per_meter_total{shoot_name=\"$shoot_name\", meter_id=\"node\"}[1h]))",
     "legendFormat": "node hours"
    }
   ]
  },
  {
   "title": "Price / 1h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cu/h" } },
   "targets": [
    {
     "expr": "sum(increase(kcr_calculation_price_per_meter_total{shoot_name=\"$shoot_name\", meter_id=\"node\"}[1h]))",
     "legendFormat": "capacity units"
    }
   ]
  },
  { "title": "PVC Meter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Size (Exact)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "sum(kcr_metering_pvc_size_exact{shoot_name=\"$shoot_name\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Size (Rounded)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "sum(kcr_metering_pvc_size_exact{shoot_name=\"$shoot_name\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "sum(kcr_metering_pvc_count{shoot_name=\"$shoot_name\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Storage Block Hours / 1h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "sbh/h" } },
   "targets": [
    {
     "expr": "sum(increase(kcr_calculation_storage_usage_per_meter_total{shoot_name=\"$shoot_name\", meter_id=\"pvc\"}[1h]))",
     "legendFormat": "storage block hours"
    }
   ]
  },
  {
   "title": "Price / 1h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cu/h" } },
   "targets": [
    {
     "expr": "sum(increase(kcr_calculation_price_per_meter_total{shoot_name=\"$shoot_name\", meter_id=\"pvc\"}[1h]))",
     "legendFormat": "capacity units"
    }
   ]
  },
  { "title": "Redis Meter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Size (Exact)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "sum(kcr_metering_redis_size_exact{shoot_name=\"$shoot_name\"}) by (tier) or 0",
     "legendFormat": "{{tier}}"
    }
   ]
  },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 35 },
   "targets": [
    {
     "expr": "sum(kcr_metering_redis_count{shoot_name=\"$shoot_name\"}) by (tier) or 0",
     "legendFormat": "{{tier}}"
    }
   ]
  },
  {
   "title": "Storage Block Hours / 1h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "sbh/h" } },
   "targets": [
    {
     "expr": "sum(increase(kcr_calculation_storage_usage_per_meter_total{shoot_name=\"$shoot_name\", meter_id=\"redis\"}[1h]))",
     "legendFormat": "storage block hours"
    }
   ]
  },
  {
   "title": "Price / 1h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cu/h" } },
   "targets": [
    {
     "expr": "sum(increase(kcr_calculation_price_per_meter_total{shoot_name=\"$shoot_name\", meter_id=\"redis\"}[1h]))",
     "legendFormat": "capacity units"
    }
   ]
  },
  { "title": "VSC Meter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Size (Exact)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "sum(kcr_metering_vsc_size_exact{shoot_name=\"$shoot_name\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Size (Rounded)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "sum(kcr_metering_vsc_size_rounded{shoot_name=\"$shoot_name\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "sum(kcr_metering_vsc_count{shoot_name=\"$shoot_name\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Usage /1h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "sbh/h" } },
   "targets": [
    {
     "expr": "sum(increase(kcr_calculation_storage_usage_per_meter_total{shoot_name=\"$shoot_name\", meter_id=\"vsc\"}[1h]))",
     "legendFormat": "storage block hours"
    }
   ]
  },
  {
   "title": "Price / 1h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "cu/h" } },
   "targets": [
    {
     "expr": "sum(increase(kcr_calculation_price_per_meter_total{shoot_name=\"$shoot_name\", meter_id=\"vsc\"}[1h]))",
     "legendFormat": "capacity units"
    }
   ]
  }
 ]
}