apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: invalid-url-secret
spec:
  output:
    http:
      dedot: true
      host:
        valueFrom:
          secretKeyRef:
            key: apiurl
            name: test
            namespace: default
      port: "9880"
      uri: /
      format: json