---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-sink-config
  namespace: kyma-system
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      debug:
        verbosity: detailed
    processors:
      memory_limiter:
        limit_mib: 40
        spike_limit_mib: 20
        check_interval: 1s
    service:
      pipelines:
        logs:
          receivers:
            - otlp
          # processors:
          #   - memory_limiter
          exporters:
            - debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-sink
  namespace: kyma-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-sink
  strategy: {}
  template:
    metadata:
      labels:
        app: log-sink
    spec:
      volumes:
        - name: config
          configMap:
            name: log-sink-config
      securityContext:
        fsGroup: 101
      containers:
        - image: otel/opentelemetry-collector-contrib:latest
          name: collector
          volumeMounts:
            - name: config
              mountPath: /etc/collector
          args:
            - --config=/etc/collector/config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-otlp-logs
  namespace: kyma-system
spec:
  ports:
    - name: grpc-otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: http-otlp
      port: 4318
      protocol: TCP
      targetPort: 4318
  selector:
    app: log-sink
