apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: telemetry-otlp-logs-fault
  namespace: kyma-system
spec:
  hosts:
    - telemetry-otlp-logs
  http:
    - fault:
        abort: # simulates: backend unresponsive
          httpStatus: 503
          percentage:
            value: 100
        delay: # simulates: backend delaying
          percentage:
            value: 100
          fixedDelay: 1s
      route:
        - destination:
            host: telemetry-otlp-logs
