{
 "title": "Istio Access Logs Test",
 "time": { "from": "2025-04-30T13:13:00.000Z", "to": "2025-04-30T13:23:00.000Z" },
 "refresh": "10s",
 "panels": [
  { "title": "Istio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total request rate handled by all istio-proxies [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(istio_requests_total{destination_service_name=\"nginx\", response_code=\"200\"}[10m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests duration milliseconds / request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_sum{__ignore_usage__=\"\"}[10m])) by (instance) / sum(rate(istio_request_duration_milliseconds_count{}[10m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request/Response bytes count [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(istio_request_bytes_count{__ignore_usage__=\"\", destination_service_name=\"nginx\", response_code=\"200\"}[10m]) ) by (instance)",
     "legendFormat": "{{instance}}-REQ"
    },
    {
     "expr": "sum(rate(istio_response_bytes_count{__ignore_usage__=\"\", destination_service_name=\"nginx\", response_code=\"200\"}[10m]) ) by (instance)",
     "legendFormat": "{{instance}}-RES"
    }
   ]
  },
  {
   "title": "Request/Response Messages Total [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(istio_response_messages_total{__ignore_usage__=\"\"}[10m]))",
     "legendFormat": "RESPONSE"
    },
    {
     "expr": "sum(rate(istio_request_messages_total{__ignore_usage__=\"\"}[10m]))",
     "legendFormat": "REQUEST"
    }
   ]
  },
  {
   "title": "Envoy Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_tx_bytes_total[10m]))",
     "legendFormat": "SUM"
    },
    {
     "expr": "rate(envoy_cluster_upstream_cx_tx_bytes_total[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_rx_bytes_total[10m]))",
     "legendFormat": "SUM"
    },
    {
     "expr": "rate(envoy_cluster_upstream_cx_rx_bytes_total[10m])",
     "legendFormat": "Total (KB)"
    }
   ]
  },
  {
   "title": "Closed Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg(envoy_cluster_upstream_cx_max_requests{__ignore_usage__=\"\"} )",
     "legendFormat": "due to maximum requests"
    },
    {
     "expr": "avg(envoy_cluster_upstream_cx_protocol_error{__ignore_usage__=\"\"} )",
     "legendFormat": "due to protocol errors"
    }
   ]
  },
  {
   "title": "Total destroyed connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "avg(envoy_cluster_upstream_cx_destroy{__ignore_usage__=\"\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Initialization Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(envoy_server_initialization_time_ms_sum{__ignore_usage__=\"\"}[$__rate_interval]) )/sum(rate(envoy_server_initialization_time_ms_count{}[$__rate_interval]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Envoy Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Bug Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "envoy_server_envoy_bug_failures",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg(envoy_server_memory_allocated{__ignore_usage__=\"\"} ) / 2^20",
     "legendFormat": "Memory Allocated (MB)"
    },
    {
     "expr": "avg(envoy_server_memory_heap_size{__ignore_usage__=\"\"} ) / 2^20",
     "legendFormat": "Heap Size (MB)"
    },
    {
     "expr": "avg(envoy_server_memory_physical_size{__ignore_usage__=\"\"} ) / 2^20",
     "legendFormat": "Physical Size (MB)"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "targets": [
    {
     "expr": "avg(envoy_server_total_connections{__ignore_usage__=\"\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(envoy_server_uptime{__ignore_usage__=\"\"} ) / 1000",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}