apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kiada
  name: kiada
spec:
  containers:
    - image: luksa/kiada:0.1
      name: kiada
      ports:
        - containerPort: 8080
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
