---
apiVersion: v1
kind: Namespace
metadata:
  name: metric-tls
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metric-tls-config
  namespace: metric-tls
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    exporters:
      debug:
        verbosity: detailed
    service:
      pipelines:
        metrics:
          receivers:
            - otlp
          exporters:
            - debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-tls
  namespace: metric-tls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-tls
  strategy: {}
  template:
    metadata:
      labels:
        app: metric-tls
    spec:
      volumes:
        - name: config
          configMap:
            name: metric-tls-config
      securityContext:
        fsGroup: 101
      containers:
        - image: otel/opentelemetry-collector-contrib:latest
          name: collector
          volumeMounts:
            - name: config
              mountPath: /etc/collector
          args:
            - --config=/etc/collector/config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: metric-tls
  namespace: metric-tls
spec:
  ports:
    - name: grpc-otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: http-otlp
      port: 4318
      protocol: TCP
      targetPort: 4318
  selector:
    app: metric-tls
---
apiVersion: v1
kind: Namespace
metadata:
  name: metric-gen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-gen
  namespace: metric-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-gen
  template:
    metadata:
      labels:
        app: metric-gen
    spec:
      containers:
        - image: ghcr.io/skhalash/examples/monitoring-custom-metrics:3d41736
          imagePullPolicy: IfNotPresent
          name: metric-gen
          ports:
            - containerPort: 8080
              name: http-metrics
              protocol: TCP
          resources:
            limits:
              memory: 100Mi
            requests:
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  name: metric-gen-metrics
  namespace: metric-gen
spec:
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: metric-gen
  type: ClusterIP
---
apiVersion: telemetry.kyma-project.io/v1alpha1
kind: MetricPipeline
metadata:
  name: sample-tls
spec:
  input:
    runtime:
      enabled: true
    prometheus:
      enabled: true
    istio:
      enabled: true
  output:
    otlp:
      endpoint:
        value: http://metric-tls.metric-tls:4317
      tls:
        cert:
          value: "cert"
        key:
          value: "key"
        ca:
          valueFrom:
            secretKeyRef:
              name: thisShouldNotExistName
              namespace: thisShouldNotExistNS
              key: thisShouldNotExistKey
