{
 "title": "Istio Access Logs Test",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Envoy Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Closed Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(envoy_cluster_upstream_cx_max_requests{__ignore_usage__=\"\"} )",
     "legendFormat": "due to maximum requests"
    },
    {
     "expr": "avg(envoy_cluster_upstream_cx_protocol_error{__ignore_usage__=\"\"} )",
     "legendFormat": "due to protocol errors"
    }
   ]
  },
  {
   "title": "Total destroyed connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "avg(envoy_cluster_upstream_cx_destroy{__ignore_usage__=\"\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg(envoy_cluster_upstream_cx_tx_bytes_buffered{__ignore_usage__=\"\"} ) / 2^10",
     "legendFormat": "Buffered"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_tx_bytes_total{__ignore_usage__=\"\"}[$__rate_interval]) ) / 2^10",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Received Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "avg(envoy_cluster_upstream_cx_rx_bytes_buffered{__ignore_usage__=\"\"} ) / 2^10",
     "legendFormat": "Buffered"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{__ignore_usage__=\"\"}[$__rate_interval]) ) / 2^10",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Envoy Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(envoy_server_memory_allocated{__ignore_usage__=\"\"} ) / 2^20",
     "legendFormat": "Memory Allocated (MB)"
    },
    {
     "expr": "avg(envoy_server_memory_heap_size{__ignore_usage__=\"\"} ) / 2^20",
     "legendFormat": "Heap Size (MB)"
    },
    {
     "expr": "avg(envoy_server_memory_physical_size{__ignore_usage__=\"\"} ) / 2^20",
     "legendFormat": "Physical Size (MB)"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "avg(envoy_server_total_connections{__ignore_usage__=\"\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Initialization Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(envoy_server_initialization_time_ms_sum{__ignore_usage__=\"\"}[$__rate_interval]) )/sum(rate(envoy_server_initialization_time_ms_count{}[$__rate_interval]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bug Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "envoy_server_envoy_bug_failures",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(envoy_server_uptime{__ignore_usage__=\"\"} ) / 1000",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}