apiVersion: v1
kind: Namespace
metadata:
  name: logs-generation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-gen-flog
  namespace: logs-generation
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: log-gen-flog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: log-gen-flog
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - log-gen-flog
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - args:
            - -b=1024 # 1KB
            - -f=json
            - -l
          image: mingrammer/flog
          imagePullPolicy: Always
          name: flog
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 50Mi